<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Compositor.Cli</RootNamespace>
    <AssemblyName>compositor-cli</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Compositor.Core\Compositor.Core.csproj" />
  </ItemGroup>
</Project>
